  
  import 'package:get/get.dart';

///Cheif Complain Part
  var chiefComplaintsList =
      {
        'Behaviour problem': ['1','2'],
        'Communication problem': [],
        'Lt side weakness': [],
        'Rt side weakness': [],
        'Facial muscle weakness': [],
        'Lower limb weakness': [],
        'Upper limb weakness': [],
        'Joint cannot perform': [],
        'Restricted movement': [],
        'Restricted gait': [],
        'Lumber muscle pain': [],
        'Back pain': [],
        'Muscle pain': [],
        'Muscle spasm': [],
        'Knee joint pain Lt': [],
        'Knee joint pain Rt': [],
        'Wrist joint pain Lt': [],
        'Shoulder joint pain Lt': [],
        'Shoulder joint pain Rt': [],
        'Traumatic pain': [],
        'Hand area pain': [],
        'Lower limb burning sensation': [],
        'Lower limb uneasiness': [],
        'Tingling sensation': [],
        'Upper back muscle pain': [],
        'Cervical muscle pain': [],
        'Hip joint pain Lt': [],
        'Hip joint pain Rt': [],
        'Buttocks pain': [],
        'Child can not sitting': [],
        'Child can not standing': [],
        'Child can not walking': [],
        'Child can not speaking': [],
        'Child have vision problem': [],
        'Child restless': [],
        'Child can not eat': [],
        'Child Tendon tightness': [],
        'Child gait problem': [],
        'Child irritating behaviour': [],
        'Nausea': [],
        'Vomiting': [],
        'Headache': [],
        'Myalgias': [],
        'Fatigue': [],
        'Fever': [],
        'Uneasiness': [],
        'Fear': [],
        'Anxiety': [],
        'Panic feelings': [],
        'Generalized Weakness': [],
        'Neurological problem': [],
        'Mental problem': [],
        'Visual problem': [],
        'Low vision problem': [],
        'Nystagmus': [],
        'Visual disturbances': [],
        'Speaking problem': [],
        'Facial problem': [],
        'Abdominal problem': [],
        'Chest problem': [],
        'Bronchial problem': [],
        'Liver problem': [],
        'Cardiovascular problem': [],
        'Skin problem': [],
        'Allergic Reaction': [],
        'Lower limb amputation': [],
        'Upper limb amputation': [],
      }.obs;


///On ExaminationPart
        var onExaminationList = {
    'Fever': [],
    'Body temperature': [],
    'Weakness': [],
    'Tired': [],
    "Muscle power average": [],
    'Sweating': [],
    'Difficulting in breathing': [],
    'Heart Rate': [],
    'Pulse': [],
    'Heart Lung problem': [],
    'Heart Lung Normal': [],
    'Breathing rate': [],
    'Blood pressure': [],
    'Skin problem/normal': [],
    'Eyes problem/normal': [],
    'Nose, mouth, throat problem/normal': [],
    'Reflexes': [],
    'Lymph nodes Normal/problem': [],
    'Abdominal problem': [],
    'Nails problem/normal': [],
    'Stroke Examination': [],
  };

  //RadioLogical Part
  var radiologicalexaminationList = {
    'Discontinuity or fracture': ['1','2'],
    'Old fracture': [],
    'Male Union': [],
    'Non union': [],
    'Callus seen': ['Soft', 'Hard'],
    'Soft': [],
    'Hard': [],
    'Fat pad': [],
    'Periosteal thickening': [],
    'Bridging': [],
    'Remodeling': [],
    'Bone marrow edema': [],
    'Occult fracture': [],
    'Displaced fragment': [],
    'Long bone fracture': [],
    'Spiral fracture': [],
    'Fracture at': [],
    'Dislocation of': [],
    'Spinal column straight': [],
    'Sacrolization': [],
    'Osteophytic changes': [],
    'Osteoporosis': [],
    'Calcification': [],
    'Tumors': [],
    'Lordosis': [],
    'Kyphosis': [],
    'Scoliosis': [],
    'Bone spurs': [],
    'Cysts': [],
    'Slipped or herniated disc': [],
    'Spinal stenosis': [],
    'Abnormal masses': [],

    'Foreign objects': [],
  };

  ///Medical HIstory part
var medicalHistoryList = {
  'Minor cuts': ['1','2'],
  'Sprain': [],
  'Strain': [],
  'Scrapes': [],
  'Bruises': [],
  'Infection': [],
  'Cough': [],
  'Diabetes': [],
  'Hypertension': [],
  'Depression': [],
  'Pneumonia': [],
  'Dermatitis': [],
  'Back pain': [],
  'Respiratory tract infection': [],
  'Tonsillitis': [],
  'Asthma': [],
  'Abdominal problem': [],
  'Arthritis': []
};

///Drug History
var drugHistoryList = {
  'Cardiovascular drug': ['1','2'],
  'Neurological drug': [],
  'Central nervous system drug': [],
  'NSAID': [],
  'Narcotic analgesic': [],
  'Antibiotic': [],
  'Antipyretic': [],
  'Antiseptics': [],
  'Hormonal drug': [],
  'Oral contraceptive': [],
  'Antimalarial': [],
  'Oncological': [],
  'Urological': [],
  'Gastrointestinal': [],
  'Reproductive': [],
  'Respiratory': [],
  'Others': []
};

///Assestive Device
var assestiveDeviceListsss = {
  'Wheel chair': ['1','2'],
  'Tri-cycle': [],
  'Electric wheelchairs': [],
  'Three wheeled scooters': [],
  'Walker': [],
  'Corner chair': [],
  'Toilet chair': [],
  'Elbow crutch': [],
  'Axillary crutch': [],
  'Digital white cane': [],
  'Tripod': [],
  'Tetrapod': [],
  'Standing frame': [],
  'Cp special chair': [],
  'Stick': [],
  'Splintages': [
    'Ankle foot orthosis',
    'Knee ankle foot orthosis',
    'Short splintage',
    'Long splintage',
    'Knee brace',
    'Long knee brace',
    'Anklet',
    'Tailor brace',
    'Lumbosacral corset',
    'Abdominal belt',
    'Clubfoot braces'
  ],
  'Eye glasses': [],
  'Magnifiers': [],
  'Communication board': [],
  'Symbol making software': [],
  'Speech generating devices': [],
  'Hearing aid': [],
  'Audiobooks': [],
  'Speech to text devices': [],
  'Text to speech devices': [],
  'Robots': [],
  'Scooters': [],
  'Talking wrist watch': [],
  'Voice activated phone dialer': [],
  'Mobility monitors': [],
  'Intellectual disability': [],
  'Hearing disability': [],
  'Deaf-blindness disability': [],
  'Cerebral palsy': [],
  'Down syndrome': [],
  'Multiple disability': [],
  'Other disability': [],
  'Medical ID bracelet': [],
  'Eye gaze and hand trackers': [],
  'Book holders': [],
  'Pill crushers': [],
  'Cochlear implants': [],
  'Prosthetic devices': [],
  'Gait belt': [],
  'Braille systems book': [],
  'Screen readers': [],
  'Large button phone': [],
  'Artificial hand': [],
  'Artificial leg': [
    'Above knee',
    'Below knee'
  ],
  'Writing aid': [
    'Pen grip',
    'Weighted pen or pencil',
    'Slanted writing board'
  ],
  'Typing aid': [],
  'Adaptive bath bench': [],
  'Adapted scissors': [],
  'Raised toilet seats': [],
  'Lowered toilet seats': [],
  'Non slip mats': [],
  'Bed positioning aid': [],
  'Pull out table next to bed, couch, chairs': [],
  'Child walker': [],
  'Normal white cane': [],
  'Hearing loops': [],
  'Picture based device': []
};
///Referred to Part
var referredToLisst = {
  'Neurological physiotherapy specialist': ['1','2'],
  'Musculoskeletal physiotherapy specialist': [],
  'Cardiopulmonary physiotherapy specialist': [],
  'Paediatric physiotherapy': [],
  'Chest physiotherapist': [],
  'Sports physiotherapist': [],
  'Pelvic floor physiotherapist': [],
  'Vestibular physiotherapist': [],
  'Hand physiotherapist': [],
  'Autism specialist': [],
  'Down syndrome specialist': [],
  'ICU physiotherapist': [],
  'Back pain physiotherapist': [],
  'Manual physiotherapist': [],
  'Geriatric physiotherapist': [],
  'Rehab consultant': [],
  'Cardiologist': [],
  'Respiratory specialist': [],
  'Neurologist': [],
  'Neuromedicine': [],
  'Neurosurgeon': [],
  'Orthopaedic surgeon': [],
  'Medicine specialist': [],
  'General surgery': [],
  'Dietician': [],
  'Nephrologist': [],
  'Urologist': [],
  'Occupational therapy specialist': [],
  'Speech and language therapist': [],
  'Prosthesis specialist': [],
  'Ophthalmologist': [],
  'Gynaecologist': [],
  'Paediatric specialist': [],
  'Neuro paediatric specialist': [],
  'Psychologist': [],
  'Counsellor': [],
  'Hepatologist': [],
  'Vascular surgeon': [],
  'Virologist': [],
  'Nutritionist': [],
  'Endocrinologist': [],
  'Pathologist': [],
  'ENT specialist': [],
  'Kinesiologist': [],
  'Oncologist': [],
  'Dermatologist': [],
  'Anaesthesiologist': [],
  'Asthma and chest specialist': [],
  'Child cardiologist': [],
  'Colorectal surgeon': [],
  'Dental specialist': [],
  'Neuro-ophthalmologist': [],
  'Laproscopic surgeon': [],
  'Hematologist': [],
  'Paediatric oncologist': [],
  'Homeopathy doctor': [],
  'Ayurvedic doctor': [],
  'Infertility specialist': [],
  'Pediatric nephrologist': [],
  'Plastic surgery specialist': [],
  'Psychiatry specialist': [],
  'Rheumatologist': [],
  'Sex specialist': [],
  'Breast specialist': [],
  'Acupuncture specialist': [],
  'Internal medicine specialist': [],
  'Geriatric medicine specialist': [],
  'Pulmonologist': [],
  'Otolaryngologist': [],
  'Radiologist': [],
  'Family physician': [],
  'Immunologist': [],
  'Emergency medicine specialist': [],
  'Gastroenterologist': [],
  'Infectious disease specialist': [],
  'Podiatrist': [],
  'Sleep medicine specialist': []
};

///Type of Disablility
var typeOfDisabilityList = {
  'Autism or autism spectrum disorder': ['1','2'],
  'Physical disability': [],
  'Mental illness leading to disability': [],
  'Visual disability': []
};

///Diagnosis Part
var diagnosisListsss= {
  'Hemiplegia Rt': ['1','2'],
  'Hemiplegia Lt': [],
  'Muscle spasm': [],
  'Lumbago': [],
  'Sciatica': [],
  'PLID': [
    'L-4,5',
    'L-5,S-1',
    'L-1,2',
    'L-2,3',
    'L-3,4'
  ],
  'PID': [
    'C-5,6',
    'C-6,7',
    'C-4.5'
  ],
  'Disc herniated': [],
  'Spinal narrowing': [],
  'Piriformis syndrome': [],
  'Back muscle spasm': [],
  'Fracture at': [],
  'Infection': [],
  'Septic arthritis': [],
  'Diabetic foot': [],
  'Spinal muscular atrophy': [],
  'Transverse myelitis': [],
  'Muscle strain': [],
  'Slipped disc': [],
  'Osteoporosis': [],
  'Rheumatoid arthritis': [],
  'Gout': [],
  'Bursitis': [],
  'Osteoarthritis': [],
  'Osteomyelitis': [],
  'Osteomalacia': [],
  'Cancer at': [],
  'Pagets disease': [],
  'Abnormal gait': [],
  'Achilles tendonitis': [],
  'Achilles tendon rupture': [],
  'Ankle injury': [],
  'Achondroplasia': [],
  'Ankylosing spondylitis': [],
  'Anterior cruciate ligament tear': [],
  'Antiphospholipid syndrome': [],
  'Arthritis of': [
    'Knee',
    'Hip',
    'Shoulder',
    'Pelvis',
    'Finger',
    'Hand',
    'Foot',
    'Cervical area',
    'Other'
  ],
  
};
