// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBiVIxCzJwLsVxbmfL8Y3b0p1V0kIvPq7Q',
    appId: '1:637978940538:web:991ce48d112550570f17c3',
    messagingSenderId: '637978940538',
    projectId: 'physiotherapy-208fa',
    authDomain: 'physiotherapy-208fa.firebaseapp.com',
    storageBucket: 'physiotherapy-208fa.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBGay6cS8VR-chk2PZ5VGaqzA5onYLW6Uw',
    appId: '1:637978940538:android:894926dca552824e0f17c3',
    messagingSenderId: '637978940538',
    projectId: 'physiotherapy-208fa',
    storageBucket: 'physiotherapy-208fa.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBBjhG91J8ItYe1sKUs5Tjlw1hALBaWUTE',
    appId: '1:637978940538:ios:a027eebdbb7d3d170f17c3',
    messagingSenderId: '637978940538',
    projectId: 'physiotherapy-208fa',
    storageBucket: 'physiotherapy-208fa.firebasestorage.app',
    androidClientId: '637978940538-eoa8gid8noovuh62sqqst779tv2tmgh3.apps.googleusercontent.com',
    iosClientId: '637978940538-m28ao15sf7fon64nm85d6hbb1rj7j4q5.apps.googleusercontent.com',
    iosBundleId: 'com.example.ePrescription',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBBjhG91J8ItYe1sKUs5Tjlw1hALBaWUTE',
    appId: '1:637978940538:ios:a027eebdbb7d3d170f17c3',
    messagingSenderId: '637978940538',
    projectId: 'physiotherapy-208fa',
    storageBucket: 'physiotherapy-208fa.firebasestorage.app',
    androidClientId: '637978940538-eoa8gid8noovuh62sqqst779tv2tmgh3.apps.googleusercontent.com',
    iosClientId: '637978940538-m28ao15sf7fon64nm85d6hbb1rj7j4q5.apps.googleusercontent.com',
    iosBundleId: 'com.example.ePrescription',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBiVIxCzJwLsVxbmfL8Y3b0p1V0kIvPq7Q',
    appId: '1:637978940538:web:6ad142edfbd594ee0f17c3',
    messagingSenderId: '637978940538',
    projectId: 'physiotherapy-208fa',
    authDomain: 'physiotherapy-208fa.firebaseapp.com',
    storageBucket: 'physiotherapy-208fa.firebasestorage.app',
  );
}
